version: "3.7"

services:
  yii2-beter-logging-php:
    container_name: "yii2-beter-logging-php"
    hostname: "yii2-beter-logging-php"
    build:
      context: .
      dockerfile: "php.dev.Dockerfile"
    volumes:
      - "./yii-test-app-src:/var/www/html"
      - "./:/yii2-beter-logging"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  yii2-beter-logging-nginx:
    container_name: "yii2-beter-logging-nginx"
    image: "nginx:1.21.6-alpine"
    ports:
      - "${HOST_NGINX_PORT:-8080}:80"
    volumes:
      - "./yii-test-app-src:/var/www/html"
      - "./deploy/data/nginx/root/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./deploy/data/nginx/root/etc/nginx/conf.d:/etc/nginx/conf.d"
    depends_on:
      - "yii2-beter-logging-php"
