version: "3.7"

services:
  yii2-beter-logging-php:
    container_name: "yii2-beter-logging-php"
    hostname: "yii2-beter-logging-php"
    build:
      context: .
      dockerfile: "php.dev.Dockerfile"
    volumes:
      - "./test-app-src:/var/www/html"
      - "./:/package-src"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  yii2-beter-logging-nginx:
    container_name: "yii2-beter-logging-nginx"
    image: "nginx:1.21.6-alpine"
    ports:
      - "${HOST_NGINX_PORT:-8080}:80"
    volumes:
      - "./test-app-src:/var/www/html"
      - "./deploy/data/nginx/root/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./deploy/data/nginx/root/etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params"
      - "./deploy/data/nginx/root/etc/nginx/conf.d:/etc/nginx/conf.d"
    depends_on:
      - "yii2-beter-logging-php"

  yii2-beter-logging-logstash:
    container_name: "yii2-beter-logging-logstash"
    image: "logstash:7.8.1"
    volumes:
      - "./deploy/data/logstash/root/usr/share/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./deploy/data/logstash/root/usr/share/logstash/pipeline:/usr/share/logstash/pipeline"
